### ISSUE TITLE
You NEED to write real docs

### ISSUE THREAD

**Issue by ghost** [JMSwag/PyUpdater-S3-Plugin#12]
it is IMPOSSIBLE for anyone without 10 years of devops experience to figure out what the hell it is that you want us to do when setting this up. For starters, how do I set all of the variables that you require but never ask for? what file or folder do they live in, and why the hell couldn't they have been part of the installer or configuration?

**Comment by JMSwag** [comment]
@ChristopherJTrent First let me say, thank you for your candor.

This is a side project that I work on for my own personal enjoyment. It's also an open source project in which everyone is free to contribute. I feel that the README for this project is sufficient, so there is no NEED for me to write real docs. Now if you feel as though there is something missing, I'd suggest you open a PR with those changes. Thanks!
