### ISSUE TITLE
Pyupdater [ERROR] Missing PYU_AWS_ID

### ISSUE THREAD

**Issue by xXxHotShotxXx** [JMSwag/PyUpdater-S3-Plugin#3]
Everytime I go to use it and run it it gives me this PYU_AWS_ID error but it doesnt have a option for this in the plugin's settings. any help?

**Comment by ArnoldGitHub** [comment]
I believe there is typo in this documentation, you should set environment variable of PYU_AWS_ID instead of PYIU_AWS_ID

**Comment by xXxHotShotxXx** [comment]
still doesnt seem to work

**Comment by ArnoldGitHub** [comment]
What is the error message?

**Comment by JMSwag** [comment]
Docs update here 506fc7aea93940cae899671c8c472b9d3c1c4e1b

@xXxHotShotxXx Please reopen if still having issues

**Comment by ghost** [comment]
Reopening because this issue was never resolved. There is no place and no way to set these values. os.environ does not support any kind of persistence and there is no way to pass values to it.

**Comment by pyrohedgehog** [comment]
Is there an updated solution to this problem? or any workaround?

**Comment by JMSwag** [comment]
@pyrohedgehog The env vars need to be set on the system or command line.
