### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by p4k1tz** [JMSwag/PyUpdater-S3-Plugin#4]
Hey,

Would be nice if we could decide the key and concatenate that to the filename. I am not really on github but am on gitlab. I forked it, but the code is so small I thought it may be more beneficial if you just made the change in this repo if you saw the value. For me, I have a single release bucket per company and software keys/folders in that bucket. I would like for the releases to go in there.

**Comment by JMSwag** [comment]
I'm not sure what's being suggested here. Please open a PR with the changes proposed.
