### ISSUE TITLE
Cannot upload to bucket root

### ISSUE THREAD

**Issue by Fizzadar** [JMSwag/PyUpdater-S3-Plugin#9]
The change [here](https://github.com/Digital-Sapphire/PyUpdater-S3-Plugin/commit/d4299d242f3450169cb8fffb09a552572ba60c3f#diff-8bc2d3a5655246dd1cd09425e3be8851R155) means that everything gets uploaded under an empty `/` folder, rather than into the bucket root as before.

**Comment by JMSwag** [comment]
Thanks for the report!

**Comment by JMSwag** [comment]
4.1.1 deployed to PyPi
